
n_latents: 47
n_hiddens: 256
n_actions: 2
num_episodes: 100_000
batch_size: 64
save_path: "./MODEL/RNN_hidden_256_layer_2_win5"  # path to save the model files

save_freq: 50  # model would be saved after every save_freq epsidoes
num_layers: 2
run_name: RNN_hidden_256_layer_2_win5
train_window : 10
timestep : 300

num_train_samples : 10000
