
n_latents: 40 #47 
input_dims: 47
n_hiddens: 256
n_actions: 2
batch_size: 64
test_batch: 12
n_sample: 64
log_interval: 50
save_interval: 10
max_step: 100_0000
n_workers: 0
run_name: VAE_MODEL
save_path: "./MODEL/VAE_MODEL"  # path to save the model files
