
extra: 'additional'
data_dir: 'datasets'
extra_dir: 'additional'
ckpt_dir: 'ckpt'
n_latents: 47
n_hiddens: 256
n_actions: 2
batch_size: 64
test_batch: 12
n_sample: 64
log_interval: 5000
save_interval: 10000
max_step: 100_0000
n_workers: 0
run_name: VAE

